import type { Metadata } from "next";
import { Roboto, Bebas_Neue } from "next/font/google";
import "@/styles/globals.css";
import { Footer } from "@/components";

const roboto = Roboto({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--roboto",
  subsets: ["latin"],
});

const bebas = Bebas_Neue({
  weight: "400",
  variable: "--bebas",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${bebas.variable}`}>
        {children} <Footer />
      </body>
    </html>
  );
}
